import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import BootstrapJS from "./components/BootstrapJS";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by GHALASS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={``}>
        <Navbar />

        <div className="m-2">{children}</div>

        <BootstrapJS />

        <Toaster />
      </body>
    </html>
  );
}
