import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BootstrapJS from "@/components/BootstrapJS";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by GHALASS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={``}>
        <Navbar />

        <div className="m-2">{children}</div>

        <Footer />

        <BootstrapJS />
      </body>
    </html>
  );
}
