@baseUrl=http://localhost:3000/api

### RESISTER USER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username":"20632",
    "password":"12345678"
}

### LOGIN USER
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username":"20632",
    "password":"12345678"
}

